version: '3.8'
services:
  vue-deep-list-builder:
    user: $HOST_UID:$HOST_GID
    build:
      context: .
    volumes:
      - ./:/app
      - cache1:/home/node/.npm
      - cache2:/home/node/.cache
    ipc: host
    ports:
      - "5173:5173"
    command: [ "npm", "run", "dev" ]
volumes:
  cache1:
  cache2:
